spring:
  profiles:
    active: dev
  cache:
    ehcache:
      config: classpath:ehcache.xml
  thymeleaf:
    cache: false
    check-template: true
    encoding: UTF-8
    servlet:
      content-type: text/html
    suffix: .html
  mvc:
    static-path-pattern: /**
logging:
  config: classpath:log4j.xml
mybatis:
  mapper-locations:
  - classpath:mappers/*.xml
  - classpath*:com/**/mapper/*.xml
