spring:
  profiles:
    active: dev
  cache:
    ehcache:
      config: classpath:ehcache.xml

logging:
  config: classpath:log4j.xml
mybatis:
  mapper-locations:
  - classpath:mappers/*.xml
  - classpath*:com/**/mapper/*.xml
