spring:
  profiles:
    active: dev
  cache:
    ehcache:
      config: classpath:ehcache.xml
  thymeleaf:
    cache: false
    check-template: true
    encoding: UTF-8
    servlet:
      content-type: text/html
    suffix: .html
  mvc:
    static-path-pattern: /**
  redis:
    host: 103.48.170.167
    port: 6379
    timeout: 20000s
    password: 123@456
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
logging:
  config: classpath:log4j.xml
mybatis:
  mapper-locations:
  - classpath:mappers/*.xml
  - classpath*:com/**/mapper/*.xml
